# 购买者条约:
# 作者: Brayn_lzh
# QQ: 390807154
# 保修规则:
#   插件永久修复错误(在合理程度内 非买方误操作 非服务端本身问题)
#   包1年内MC版本更替修复
#   对修改过代码的不保修
#   需要保修时请说明问题 务必附上报错内容
#   若需要添加新功能将进行最低量的收费
# 你可以:
#   1.声明这个插件是私用的
#   2.举报他人服务器剽窃该插件
#   3.利用本插件盈利
#   4.修改本插件代码
# 你不可以:
#   1.声明这个插件是你写的
#   2.不能通过卖本插件盈利
# 有可能在不通知您的情况下对本插件进行修改后卖给他人(一般都会通知 并且将返回部分钱)
# 对应不在本条约里的事项请向我联系
name: Occupy
author: Bryan_lzh
description: '开发者QQ:390807154'
main: br.occupy.Main
depend: [BrAPI,HolographicDisplays]
version: 1.0

commands:
    Occupy:
        aliases: [oc]
        description: 主命令
        usage: |
            §6/<command> create [区域名] [显示名(可颜色代码)] >> 创建一个新的区域(两点已预先用特殊道具选择过)
            §6                                          §l注意 你输入命令的时候所在点将会作为全息显示点
            §6/<command> get >> 获得选点道具
            §6/<command> remove [区域名] >> 移除一个区域
            §6/<command> list >> 显示所有区域
            §6/<command> tp [区域] 传送到一个区域的最高点